### ISSUE TITLE
Multiuser Support and Other To-Do

### ISSUE THREAD

**Issue by ken-cheng-valon** [ScazLab/ros_speech2text#8]
* [ ] Allow user to choose audio device if multi_user interactive mode enabled
* [ ] Allow user to specify user_id if multi_user interactive mode enabled
* [x] Make param private
